--require "user.conf.statusline"
-- require "user.conf.auto-command"
-- require "user.conf.toptabline"
-- require "user.conf.nvim-gps"
require "user.conf.alpha"
-- require "user.conf.nvim-navic"
require "user.conf.nvim-bqf"
--require "user.conf.filetype"
require "user.conf.diffview"
-- require "user.conf.copilot"
--require "user.conf.sniprun"
-- require "user.conf.dashboard"
-- require "user.conf.windowpicker" -- WARNING : It doesn't seems to work 
require "user.conf.neovim-session-manager"
require "user.conf.aerial"
require "user.conf.pantran"
require "user.conf.auto-pairs"
require "user.conf.cmp"
--require "user.conf.snippy"
-- require "user.conf.nvim-tree"
require "user.conf.neo-tree"
require "user.conf.noice"
-- require "user.conf.chatgpt"
--require "user.conf.galaxy" 
--require "user.conf.lualine"
require "user.conf.git"
-- require "user.conf.notify"
require "user.conf.cmp-tabline"
-- require "user.conf.copilot"
require "user.conf.telescope"
require "user.conf.treesitter"
require "user.conf.treesitter-context"
require "user.conf.comments"
require "user.conf.numb"
require "user.conf.functions"
-- require "auto-pandoc"
-- require "user.conf.wilder"
require "user.conf.todo-comments"
require "user.conf.indent_blankline"
require "user.conf.mini_indentscope"
-- require "user.conf.toggleterm"
require "user.conf.fidget"
require "user.conf.whichkey"
require "user.conf.neovim-cmake"
--require "user.conf.nvim-spectre"
require "user.conf.nvim-coloizer"
require "user.conf.smoothcursor"
require "user.conf.dressing"
require "user.conf.bufferline"
require "user.conf.trouble"
require "user.conf.vim-illuminate"
require "user.conf.legendary"
-- require "user.conf.winbar"
-- require "user.conf.impatient"
require "user.conf.browse"
-- require "user.conf.autosave"
