require "module.tool.file"
require "module.tool.whichkey"
require "module.tool.outline"
require "module.tool.cmake"
require "module.tool.replace"
require "module.tool.Git"
require "module.tool.comment"
require "module.tool.neodim"
require "module.tool.todo"
require "module.tool.session-manager"
require "module.tool.windows"
-- require "module.tool.sniprun"
require "module.tool.bookmark"
require "module.tool.filetype"
require "module.tool.pantran"
-- require "module.tool.chatgpt"
require "module.tool.auto-save"
-- require "module.tool.compiler"
-- require "module.tool.bqf"
